version: '3.8'

services:
  django:
    build: .
    container_name: django_app
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A news_web worker --loglevel=info
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0